# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40e0946fd7e242158bf0973faa2a04951a89aa257ddd310f815baad0e1ee610034d9b7d9aa8d85f0e6c0253c12b1f19fa618d5883ae5642a7ca8d2c62f1f5fe7

test:
  secret_key_base: f90f0c14a7f9216ad44c5df3caf946b030df100797ed7483c03b615cc4c8002e492f52cfb32ccecccda983c7e3e4fc7c7d1f5c3050f356b6598da053ddd3a34f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
